name: PKGBUILD

on:
  workflow_call:
    inputs:
      path:
        description: 'Location of the PKGBUILD recipe, relative to the root of the repository.'
        required: true
        type: string
      test:
        description: 'Commands to test the tool after installing the package.'
        required: true
        type: string
      systems:
        description: 'Space separated list of systems to build and test the tool on.'
        required: false
        type: string
        default: 'msys mingw32 mingw64 ucrt64 clang32 clang64'

jobs:


  win-jobs:
    name: â¬œ Generate list of MSYS2 jobs
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.jobs.outputs.jobs }}
    steps:
    - name: Generate list of jobs
      shell: python
      id: jobs
      run: |
        icons = {
          'msys':    'ğŸŸª',
          'mingw32': 'â¬›',
          'mingw64': 'ğŸŸ¦',
          'ucrt64':  'ğŸŸ¨', # Experimental!
          'clang32': 'ğŸŸ«',
          'clang64': 'ğŸŸ§', # Experimental!
        }
        jobs = [
            {'sys': sys.lower(), 'icon': icons[sys.lower()]}
            for sys in '${{ inputs.systems }}'.split(' ')
        ]
        print(f"::set-output name=jobs::{jobs!s}")


  win-makepkg:
    needs: win-jobs
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.win-jobs.outputs.jobs) }}
    name: ğŸš§${{ matrix.icon }} ${{ matrix.sys }} | makepkg
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: ${{ matrix.sys }}
    steps:

    - name: 'âš™ï¸ git config'
      run: git config --global core.autocrlf input
      shell: bash

    - name: 'ğŸ§° Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: git base-devel tree
        pacboy: toolchain:p

    - name: 'ğŸš§ Build package'
      run: |
        cd ${{ inputs.path }}
        makepkg-mingw --noconfirm --noprogressbar -sCLf

    - name: 'ğŸ“¤ Upload artifact: package'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.sys }}-TOOL
        path: examples/pkgbuild/*.zst

    - name: 'ğŸ” Show package content'
      run: |
        mkdir tmp
        cd tmp
        tar -xf ../${{ inputs.path }}/*.zst
        tree .


  win-test:
    needs:
      - win-jobs
      - win-makepkg
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.win-jobs.outputs.jobs) }}
    name: ğŸš¦${{ matrix.icon }} ${{ matrix.sys }} | test
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true

    - name: 'ğŸ“¥ Download artifact: package'
      uses: actions/download-artifact@v2
      with:
        path: .
        name: ${{ matrix.sys }}-TOOL

    - name: 'ğŸ› ï¸ Install package'
      run: pacman -U --noconfirm --noprogressbar *.zst

    - name: 'ğŸš¦ Test package'
      run: ${{ inputs.test }}
