name: PKGBUILD

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the package/tool, to be appended to artifact names.'
        required: true
        type: string
      matrix:
        description: 'JSON list of systems to build and test the tool on.'
        required: true
        type: string
      path:
        description: 'Location of the PKGBUILD recipe, relative to the root of the repository.'
        required: true
        type: string
      test:
        description: 'Commands to test the tool after installing the package.'
        required: true
        type: string

permissions:
  contents: read

jobs:


  win-makepkg:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.matrix) }}
    name: ğŸš§${{ matrix.icon }} ${{ matrix.sys }} | makepkg
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: ${{ matrix.sys }}
    steps:

    - name: 'âš™ï¸ git config'
      run: git config --global core.autocrlf input
      shell: bash

    - name: 'ğŸ§° Checkout'
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: ğŸ“¥ Download artifact
      uses: actions/download-artifact@v5
      with:
        name: action

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: ./
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: git base-devel tree
        pacboy: toolchain:p

    - name: 'ğŸš§ Build package'
      env:
        PKGBUILD_PATH: ${{ inputs.path }}
      run: |
        cd "$PKGBUILD_PATH"
        makepkg-mingw --noconfirm --noprogressbar -sCLf

    - name: 'ğŸ“¤ Upload artifact: package'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.sys }}-${{ inputs.name }}
        path: ${{ inputs.path }}/*.zst

    - name: 'ğŸ” Show package content'
      env:
        PKGBUILD_PATH: ${{ inputs.path }}
      run: |
        mkdir tmp
        cd tmp
        tar -xf ../"$PKGBUILD_PATH"/*.zst
        tree .


  win-test:
    needs: win-makepkg
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.matrix) }}
    name: ğŸš¦${{ matrix.icon }} ${{ matrix.sys }} | test
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: ğŸ“¥ Download artifact
      uses: actions/download-artifact@v5
      with:
        name: action

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: ./
      with:
        msystem: ${{ matrix.sys }}
        update: true

    - name: 'ğŸ“¥ Download artifact: package'
      uses: actions/download-artifact@v5
      with:
        path: .
        name: ${{ matrix.sys }}-${{ inputs.name }}

    - name: 'ğŸ› ï¸ Install package'
      run: pacman -U --noconfirm --noprogressbar *.zst

    - name: 'ğŸš¦ Test package'
      run: ${{ inputs.test }}  # zizmor: ignore[template-injection]
